kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Values.namespace }}
data:
  {{ .Values.configMap.subPath }}: |-
{{ .Files.Get "rabbitmq-definitions.json" | indent 4 }}