apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
spec:
  ports:
  - name: http
    port: {{ .Values.service.superset.port }}
    protocol: TCP
    targetPort: {{ .Values.containerPort.superset }}
  selector:
    app: {{ .Chart.Name }}
  type: ClusterIP
