{{- range $namespace, $nmd := .Values.namespaces }}
---
kind: Secret
apiVersion: v1
metadata:
  name: aws-credential-secret
  namespace: {{ $namespace }}
type: Opaque
data:
  aws-access-key-id: {{ $.Values.credentials.access_key_id | b64enc | quote }}
  aws-secret-access-key: {{ $.Values.credentials.secret_access_key | b64enc | quote }}
  aws-default-region: {{  $.Values.credentials.default_region | b64enc | quote }}
{{- end }}