apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
  # should be unnecessary
  # annotations:
  #   service.beta.kubernetes.io/aws-load-balancer-ssl-cert: {{ .Values.service.cert }}
  #   service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
spec:
  ports:
  - name: http
    port: {{ .Values.service.service.port }}
    protocol: TCP
    targetPort: {{ .Values.containerPort.service }}
  selector:
    app: {{ .Chart.Name }}
  type: ClusterIP

