enable_remote_logging: true
is_local: false
use_staging_db: false
database:
  service:
    url: postgresql://SERVICE_METADATA_POSTGRES_USERNAME:SERVICE_METADATA_POSTGRES_PASSWORD@SERVICE_METADATA_POSTGRES_HOSTNAME/SERVICE_METADATA_POSTGRES_DATABASE_NAME

  provisioner:
    url: postgresql://SERVICE_METADATA_POSTGRES_USERNAME:SERVICE_METADATA_POSTGRES_PASSWORD@SERVICE_METADATA_POSTGRES_HOSTNAME/SERVICE_METADATA_POSTGRES_DATABASE_NAME

chunk_size: 3