apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.redis }}-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app.redis }}
spec:
  ports:
    - name: http
      port: {{ .Values.service.redis.port }}
      protocol: TCP
      targetPort: {{ .Values.containerPort.redis }}
  selector:
    app: {{ .Values.app.redis }}
  type: ClusterIP
