apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-load-balancer
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    {{ if .Values.service.cert }}
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: {{ .Values.service.cert }}
    {{ else }}
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: {{ .Values.global.aws_load_balancer_cert }}
    {{ end }}
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.service.service.port }}
      targetPort: {{ .Values.containerPort.service }}
  selector:
    app: {{ .Chart.Name }}
